### ISSUE TITLE
Program Terminates When making multiply or division operation

### ISSUE THREAD

**Issue by mohamedelshorbagy** [AhmedSadek60/AsuMathLabG19#4]
When using operation like * or / 
if matrices is not square it terminates all the program and I just want to have a little message telling me the operation can't be done

![1111](https://user-images.githubusercontent.com/22217011/33223937-5b26eda4-d16d-11e7-8a3e-10a17fe831de.png)

**Comment by amr-galal** [comment]
When the matrix is not invertible it throws an error:
![image](https://user-images.githubusercontent.com/23275727/33224091-91e76174-d16e-11e7-9cc3-a094b94475d5.png)

But we only need a message telling the user that the matrix is just not invertible and division can't be done, right? Now that's easy

As for the multiplication, it's valid: 3 x 1 * 1 x 3, should return a 3 x 3 matrix.
So the problem here is different!

**Comment by mohamedelshorbagy** [comment]
Yes , That's Right firstly finish the Division then finish the Multiplication Problem

**Comment by amr-galal** [comment]
Handled diving by a non square matrix here in the second attempt:
![image](https://user-images.githubusercontent.com/23275727/33224323-0451ab0a-d171-11e7-9b7a-b57f99a82c6e.png)

Now the first attempt is an error thrown from mul() function because I'm multiplying:
1 x 3 * 2 x 3
